### ISSUE TITLE
[BUG] Fix explain policy_id setting

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/index-management#108]
**Workaround**

If you are affected by this, please update your external code/scripts to use either the "policy_id" key (preferred) or the "index.plugins.index_state_management.policy_id" key (not preferred). _The reason for the index.plugins.index_state_management.policy_id is not preferred is because this is not actually used anywhere anymore internally. It is purely for external compatibility in the API response._

**Describe the bug**
The explain response had some legacy logic where we continued to populate the individual responses with the policy_id index setting (which is deprecated and not used anymore) and the policy_id. This was for making sure we didn't break anyones code/scripts that checked that specific key field.

When we migrated to OpenSearch it seems there was a miss where we accidentally changed the response key in the individual explain responses to the new plugins.index_state_management.policy_id name instead of the old opendistro.index_state_management.policy_id. This could be considered a breaking change, we should revert it back.

https://github.com/opensearch-project/index-management/blob/main/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/explain/ExplainResponse.kt#L74

**Comment by dbbaughe** [comment]
For reference, an example of a single explain response item looks like this:
```
"example-index" : {
    "index.opendistro.index_state_management.policy_id" : "some-policy",
    "index" : "example-index",
    "index_uuid" : "123456abcdefg",
    "policy_id" : "some-policy",
    "policy_seq_no" : 2344,
    "policy_primary_term" : 1,
    "rolled_over" : false,
    "index_creation_date" : 1627921576000,
    "state" : { ... },
    "action" : { ... },
    "step" : { ... },
    "retry_info" : { ... },
    "info" : { ... }
}
```

Previously we allowed users to set the policy on an index through an index level setting called `"index.opendistro.index_state_management.policy_id"`. We have since removed that option so it is not used anymore, but we decided to keep the index setting key in the response as people might have been relying on its presence for their own external code/scripts.

With the migration to OpenSearch it looks like it was erroneously changed to this:
```
"example-index" : {
    "index.plugins.index_state_management.policy_id" : "some-policy",
    "index" : "example-index",
    "index_uuid" : "123456abcdefg",
    "policy_id" : "some-policy",
    "policy_seq_no" : 2344,
    "policy_primary_term" : 1,
    "rolled_over" : false,
    "index_creation_date" : 1627921576000,
    "state" : { ... },
    "action" : { ... },
    "step" : { ... },
    "retry_info" : { ... },
    "info" : { ... }
}
```

**Comment by dblock** [comment]
Ouch, now we have it both ways in a GA release. Is the right solution to have both now?

**Comment by dbbaughe** [comment]
Bleh, yeah if we have to consider the fact that people could have downloaded OS 1.0 or migrated to it and started using or updated their external code/scripts to the new key setting, then sure we might need to have both now. Not the happiest with it since they are literally not used and was purely some old deprecated/legacy setting and it was just polluting the response. So having two just makes it a bit worse, but I agree.. we might need to just add them both in now unless people are OK with us removing this one that got accidentally introduced.

**Comment by dblock** [comment]
+ we need a test/spec that records output from REST API responses and compares them version-over-version

**Comment by nknize** [comment]
GA isn't a big issue... Things like this will happen and we respond w/ a quick bug fix. 


Instead of reverting can we just add a "compatibility" flag to the `index-management` plugin like we did w/ core opensearch? It's legacy logic anyway to ensure forward compatibility w/ customer code/scripts. In compatibility mode just have it use the old `opendistro.index_state_management.policy_id`. 

Alternatively, add the `opendistro` key/value alongside the new flag?

**Comment by dblock** [comment]
> GA isn't a big issue... Things like this will happen and we respond w/ a quick bug fix.
> 
> Instead of reverting can we just add a "compatibility" flag to the `index-management` plugin like we did w/ core opensearch? It's legacy logic anyway to ensure forward compatibility w/ customer code/scripts. In compatibility mode just have it use the old `opendistro.index_state_management.policy_id`.

We preserved all opendistro names for indexes and API responses across the board, so I don't recommend introducing options like this in this and every plugin. We might want to piggyback on the cluster bcw setting in 1.x and standardize this across all plugins, but it's a separate conversation from here.

**Comment by nknize** [comment]
> We might want to piggyback on the cluster bcw setting in 1.x and standardize this across all plugins

That's to spoof nodes to an old ES version for node compatibility. Relying on that as the "global" parameter for all plugins doesn't scale or add flexibility.

**Comment by elfisher** [comment]
> > Alternatively, add the `opendistro` key/value alongside the new flag?
> 
> Yes, this seems like the safer option.

Agreed. I think we should support both. If we want to have a single one going forward, I'd suggest making that change in 2.0.

**Comment by nknize** [comment]
> I'd suggest making that change in 2.0.

It should be carried until 2.0. Breaking changes shouldn't occur in minor releases. 



> we should support both.

We shouldn't support both. We should support a compatibility mode quickly released in a 1.0.1 bug fix. The index-management plugin should implement this and then we should open a separate "feature" issue to make that "compatibility" logic available across plugins.

**Comment by nknize** [comment]
I think the index-management plugin should introduce a new cluster API setting like we did with [`compatibility.override_main_response_version`](https://github.com/opensearch-project/OpenSearch/pull/847).  Call it `ilm.compatibility.include_legacy_policy_id` or something that when set to `true` includes the old setting alongside the new. Throw deprecation warnings around it, and carry it through the entire 1.x line. This will introduce a precedence for other plugins to follow if breaking changes like this happen in the future.

**Comment by dbbaughe** [comment]
I'm not sure I completely follow @nknize, if we introduce something like that then are we saying we will default it to false? If so that is still a breaking change across migrations to 1.x from Elasticsearch/ODFE as the key disappears from the response.

If we default true to not introduce a breaking change then it simply means the user has the option of setting the new setting to false and remove one of the extra keys from the explain response. The mental overhead from this doesn't seem worth the result unless I'm missing something.

And how does it introduce a good precedence for other plugins to follow if this happens again? It still means the current released version will have a breaking change and a patch release will be needed to fix it that introduces a compatibility setting to let them toggle the breaking change which presumably would default to true to not break by default.

So instead of two settings supported w/ one (or all) removed in the next major version we would have both settings and a compatibility setting, so three, and toggling behavior which could cause confusion.

**Comment by nknize** [comment]
> that is still a breaking change across migrations to 1.x

It defaults to false and affected users set it to true using cluster API setting:

```
PUT /_cluster/settings
{
  "index-management" : {
    "compatibility.include_legacy_policy_id" : true 
  }
}
```

> And how does it introduce a good precedence for other plugins to follow if this happens again?

I suggest opening a new `feature` issue that allows "compatibility" settings to be a runtime behavior (e.g., through opensearch.yml mechanism, compatibility index, or something similar) that fixes the problem without requiring an entire bugfix release. Lets make the fix worthwhile instead of spending resources releasing a hack.

**Comment by dbbaughe** [comment]
> It defaults to false

@nknize I'm not sure I agree, it would mean that the next patch release we are still hiding the key that introduced the breaking change and so users that are just upgrading to the affected version are going to be hit by the breaking change when we could have at least defaulted that approach to true so they don't see a breaking change. Why would we want to default it to false in this case?

**Comment by nknize** [comment]
> Why would we want to default it to false in this case?

This is trappy for users unaffected by the breaking change; affected users (a smaller percent) should upgrade and opt-in to ensure compatibility. Defaulting to true is leniency - an ally of disaster.

**Comment by dbbaughe** [comment]
But, you're trying to create a generalization for all plugins to follow and can't always assume the affected users are a smaller percent of the plugin's user base. And regardless in this scenario the affected users being a small percent of ISM users.. if we have the option of fixing it so people unaware of it aren't affected when they upgrade versus not I think we should fix it..

The way I am looking at the two options proposed so far are:

1. We release 1.0.1 with the change to add back opendistro setting so we have both side by side. The amount of users upgrading directly to 1.0.0 should drastically drop once a patch version is released as we should be defaulting them to the newer 1.0.x version for 1.0. All users that are not aware of the issue and upgrade to 1.0.1 or 1.1.0 when released will not have anything broken if they were using the opendistro prefix. And all users that were on 1.0 that have since started using it or updated scripts/code to use it will be unaffected as we will continue to support it until 2.0.

2. We release 1.0.1 with a compatibility feature that lets you toggle the opendistro prefix to be added back to the response. It defaults to false. We will continue to have users that upgrade to 1.0.1 from ODFE/Elasticsearch and going forward once we release 1.1.0 will have users upgrading to it. All of these users that use ISM and relied on this setting will experience their scripts/code breaking. It's operational overhead for us and a bad user experience.

I'm heavily leaning towards option 1 in this case so far. The alternative is option 2 defaulting to true, but then I question it's usefulness.. more specifically on what benefit it's providing to us and the customer.

**Comment by nknize** [comment]
> if we have the option of fixing it so people unaware of it aren't affected when they upgrade

This is exactly why it should be opt in. It's a deprecated setting. Users should be aware of this. I do not agree with silent behavior.


> We release 1.0.1 with a compatibility feature that lets you toggle the opendistro prefix

I vote option two. No silent behaviors on a feature that's deprecated and should have deprecation warnings. Opt in is informative and requires users to proactively aknowledge a forward compatibility behavior that will be removed in version 2.

**Comment by nknize** [comment]
Either way, we should add the compatibility setting; even if the consensus is to default to `true`. 

At least then it's part of the cluster setting API which is easy to change without restart.

**Comment by dblock** [comment]
@nknize We made promises about backwards compatibility and broke that promise by renaming a field. We don't want this new name, we should have never renamed the field. So this is a bug, not a feature. I think we should return the old field name in 1.1 to fix the bug, and the second question is how do we deal with customers on 1.0 that may accidentally be relying on the new name: Drew is proposing we return the wrong name that we should have never used in the entire 1.x line without any switches or options, at the same time. Do you strongly disagree that's the way to go?

**Comment by nknize** [comment]
> We don't want this new name

All the more reason to not saddle it along side the opendistro name and have to carry both through the entire 1.x line. That's the worst thing to do, and will cause more confusion for new adopters. 



> this is a bug, not a feature

Except these kind of bugs happen more often than not and a mechanism to handle them in the future without requiring an entire release is the silver lining to come out of this fix. We should not engage an entire 1.0.1 release to introduce a side by side hack that causes more confusion. We should engage a release process to fix the bug along with a mechanism to absorb these "oopsies" in the future.



>  I think we should return the old field name in 1.1 to fix the bug

If the general consensus is to fix the bug with a side by side hack then it needs to go into a 1.0.1 patch release, not 1.1.0 feature release. 



> Drew is proposing we return the wrong name that we should have never used in the entire 1.x line without any switches or options, at the same time. Do you strongly disagree that's the way to go?



Yes. I strongly disagree. At minimum there should be deprecated options. At best there should be a runtime mechanism. GA is out. No need to rush a hack that engages a large release work force (because it does at this point) without fixing the main problem. We'll just be back in this same situation with a different "oops".
