### ISSUE TITLE
Automated upgrade testing from previous versions

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/index-management#111]
We want to ensure compatibility with previous versions of ODFE and Elasticsearch as we continue to make changes and as long as there is a path for users to upgrade from. Right now for the official OS 1.0 release we only tested 7.10 -> OS 1.0 and we still have a lot of untested versions. Since we will also support upgrades e.g. for 7.10 -> OS 1.1 we should add some automated upgrade tests into Index Management for these future paths and also take the time to add the older versions pre 7.10 -> OS 1.x.

**Comment by bowenlan-amzn** [comment]
We have bwc test in the repo running now
