### ISSUE TITLE
Typo in message at Line 421 of AttemptRolloverStep.kt

### ISSUE THREAD

**Issue by lmako-aws** [opensearch-project/index-management#1123]
Hi,

Just wanted to let you know that there is a typo at Line 421 of AttemptRolloverStep.kt

https://github.com/opensearch-project/index-management/blob/042f72841ff85032beecc20c3f9338161af2ab42/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollover/AttemptRolloverStep.kt#L421

The message says `Successfully rolled over but failed to copied alias from [index=$index] to [index=$newIndex]` instead of `Successfully rolled over but failed to copy alias from [index=$index] to [index=$newIndex]`

Thanks,
Laz

**Comment by sarthakaggarwal97** [comment]
@lmako-aws this seems like a genuine typo, would you wanna raise a PR for this?

**Comment by lmako-aws** [comment]
@sarthakaggarwal97 It definitely is. I just thought I'd let you know. I'm happy to leave it with you guys and you can decide whether you address it or not.
