### ISSUE TITLE
[BUG] indices not being displayed in ISM

### ISSUE THREAD

**Issue by Nurarao** [opensearch-project/index-management#1175]
**Describe the bug**

The S3 logs are not being indexed in the OpenSearch dashboard despite successful triggering of the Lambda function upon bucket uploads, as evidenced by CloudWatch logs.

**To Reproduce**

Upload logs to the specified S3 bucket.
Lambda function triggers upon upload.
Check OpenSearch dashboard for indexed logs.

**Expected behavior**

The logs uploaded to the S3 bucket should be indexed in the OpenSearch dashboard.

**OpenSearch Version**

2.13(latest)

**Dashboards Version**

2.13.0

**Screenshots**

<img width="1421" alt="Screenshot 2024-05-24 at 3 50 26 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/103449947/d417b083-3398-49cd-b984-c7ed504f0539">

Host/Environment (please complete the following information):

OS: AWS Lambda
Browser and version: Safari. Version 17.2.1

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)
