### ISSUE TITLE
[FEATURE] Set index-management plugin 3.0.0 baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by reta** [opensearch-project/index-management#1181]
### Is your feature request related to a problem? Please describe

Set `index-management` plugin 3.0.0 baseline JDK version to JDK-21

### Describe the solution you'd like

See please https://github.com/opensearch-project/OpenSearch/issues/10745

### Related component

Build

### Describe alternatives you've considered

N/A

### Additional context

See please https://github.com/opensearch-project/OpenSearch/issues/14011

**Comment by Hailong-am** [comment]
done with https://github.com/opensearch-project/index-management/pull/1276
