### ISSUE TITLE
[FEATURE] Support searches across raw data indices and rollup indices together

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/index-management#1213]
**Is your feature request related to a problem?**
Currently, we do not support searches if the same request has both raw indices and the indices with associated rollup job. We return the exception upon [validation](https://github.com/opensearch-project/index-management/blob/main/src/main/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptor.kt#L144-L157) if both types of indices are present in the request. 

**What solution would you like?**
Support searches across both all indices in order to query / aggregate results irrespective of whether the rollup job is assigned or not to a particular index.

**Comment by mgodwan** [comment]
Is there any historical reason around why we are not supporting this? Is this just because of query rewrite we trigger via rollup interceptor?

Also, we would need to test this flow and verify that the aggregations across indices (raw, rolled up) yield correct results.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross)

**Comment by manojfaria** [comment]
In the absence of this feature, users of opensearch have to evaluate the option of issuing two separate queries i.e. one query to the raw index, and one query to the rollup-indices. 

Some customers/users of OpenSearch are reporting this double querying (once to raw, and additional query to rollup indices) as a major hurdle, as this workaround of separately querying raw and rollup indices requires significant code change to their product/app.
