### ISSUE TITLE
[BUG] some system indices growing indefinitely

### ISSUE THREAD

**Issue by soorajambadi** [opensearch-project/index-management#1218]
### Describe the bug

I have observed that for some system indices such as below, may grow indefinitely: 
- .opendistro-ism-config
- .opendistro-job-scheduler-lock

Even if they continue to grow, I see, they have a lot of deleted documents.

### Related component

Indexing

### To Reproduce

Observation using the metric: elasticsearch_indices_store_size_bytes_total

### Expected behavior

The system indices should not grow indefinitely

**Comment by vikasvb90** [comment]
@dblock Why was this transferred to indexing? 
System indices belong to different plugins, first belongs to ISM and second belongs to job-scheduler. Also, I don't see enough details on how it was concluded that index growth was not organic but was potentially a bug.

**Comment by vikasvb90** [comment]
@soorajambadi You may need to look into what data these indices contain and whether growth in data makes sense  or it is a leak somewhere. For e.g., in a cluster where there are too many indices getting rolled over and created, growth in data would make sense.

**Comment by soorajambadi** [comment]
@vikasvb90 I did some analysis to check if the growth is related to increase in the number of indices in the cluster. To my limited knowledge the system index .opendistro-job-scheduler-lock stores (in my case) lock information of different jobs. This has following fields: job_index_name, job_id, lock_time, lock_duration_seconds, and released. When I did:
`GET /.opendistro-job-scheduler-lock/_search`
I got 39 hits and all has job_index_name value .opendistro-ism-config, but different job_id values. 
When I did `GET /.opendistro-ism-config/_search ` I got the same number of managed indices with "_id" corresponds to previously found job_id values.

In summery, the indices are not growing and the .opendistro-job-scheduler-lock index contains number of documents corresponding to the number of non-system indices.

Given the index number is constant during the time of measure, the .opendistro-job-scheduler-lock size still grows, which brings the suspicion. Attaching the 24 hour size growth with constant index number (39):
<img width="1306" alt="growth_per_day" src="https://github.com/user-attachments/assets/2d19139b-8896-495d-a270-3349689b65ea">

**Comment by dhwanilpatel** [comment]
Looks like some issue with the job scheduler plugin, as it's system index is the growing. 

@opensearch-project/admin  Can we move it to https://github.com/opensearch-project/job-scheduler?

**Comment by cwperks** [comment]
@soorajambadi @dhwanilpatel What version of OpenSearch are you running?

**Comment by cwperks** [comment]
> Even if they continue to grow, I see, they have a lot of deleted documents.

Found a forum post that may be relevant: https://forum.opensearch.org/t/indices-become-bloated-not-deleting-deleted-docs-and-old-doc-versions/11019

Is it possible that the `index.soft_deletes.retention_lease.period` setting is set to a non-default value?

**Comment by soorajambadi** [comment]
@cwperks thanks for the details. We are running OpenSearch 1.3.x, although there are plans for an upgrade.

Indeed I can see a lot of documents marked for deletion and it grows. I see after few days it drops to a lower value (Zig-zag nature) which purges deleted docs during a merge.
Since the root cause is clear and is not a bug but how OpenSearch works, I think the issue can be closed.
