### ISSUE TITLE
[BUG] Project integration tests require same version of plugins to be checked in

### ISSUE THREAD

**Issue by dblock** [opensearch-project/index-management#123]
**Describe the bug**

Currently the following files are checked in.

```
src/test/resources/index-management/opendistro-index-management-1.13.0.0.zip
src/test/resources/notifications/opensearch-notifications-1.1.0.0-SNAPSHOT.zip
src/test/resources/job-scheduler/opensearch-job-scheduler-1.1.0.0-SNAPSHOT.zip
```

These are moving targets. Furthermore they are of the same release, while one would want to run integration tests against the released versions of any dependency. Which causes a catch-22 problem.

**Expected behavior**

These files should be deleted. One solution would be to download them during build. Another would be to build them (#119 tried to do that). 

**Additional context**

Consider the developer experience that wants to check out this repo and just run `./gradlew integTest` successfully.

**Comment by downsrob** [comment]
In the 1.3 branch we currently are still using the job scheduler resource in testing https://github.com/opensearch-project/index-management/tree/main/src/test/resources/job-scheduler

**Comment by ylwu-amzn** [comment]
AD using RCF jar and Protostuff jar https://github.com/opensearch-project/anomaly-detection/tree/1.3/lib, @dblock , we are going to revert the change to remove protostuff.

And we have job scheduler jar https://github.com/opensearch-project/anomaly-detection/tree/1.3/src/test/resources/job-scheduler, and BWC test https://github.com/opensearch-project/anomaly-detection/tree/1.3/src/test/resources/org/opensearch/ad/bwc/job-scheduler

**Comment by ylwu-amzn** [comment]
Same RCF issue for `ml-commons`, we have local RCF jar file https://github.com/opensearch-project/ml-commons/tree/1.3/ml-algorithms/lib. Will pull from Maven once 2.x published

**Comment by dblock** [comment]
@ylwu-amzn Same problem we're checking in the JARs into AD, https://github.com/opensearch-project/anomaly-detection/issues/433

**Comment by prudhvigodithi** [comment]
Hey @downsrob, @ylwu-amzn, @dblock we have now, a mechanism to publish the zips to maven repo using [opensearch.pluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip), we can delete the zips from checking in to source repo (unless i'm missing something) and can be dowloaded during runtime using maven coordinates once they are published.

**Comment by ylwu-amzn** [comment]
Thanks @prudhvigodithi , I think @amitgalitz has removed local zip file from AD, check https://github.com/opensearch-project/anomaly-detection/pull/487 and  https://github.com/opensearch-project/anomaly-detection/pull/505. We are using latest build link and cloudfront download link, check https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L37
```
        job_scheduler_build_download = 'https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/' + opensearch_no_snapshot +
                '/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-job-scheduler-' + plugin_no_snapshot + '.zip'
...

        bwcOpenDistroJSDownload = 'https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/' +
                'opendistro-job-scheduler/opendistro-job-scheduler-1.13.0.0.zip'
```

@prudhvigodithi should we move to maven? Any benefit?

**Comment by prudhvigodithi** [comment]
Hey @ylwu-amzn yes pulling zips from maven is the right way to go, as you dont need to manage any custom code moving forward, as using this [opensearch.pluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip) the zips will be published to maven repo and can be fetched with right artifcatID, groupID and version.

**Comment by downsrob** [comment]
Index Management has replaced checked-in ZIPs with dynamic dependencies as per https://github.com/opensearch-project/index-management/issues/305. Now, this issue is not specifically related to that behavior, but should be used to track the progress of getting integration tests to run against dependencies of different versions

**Comment by prudhvigodithi** [comment]
Hey @downsrob, looks to me like its using the latest URL and some parse logic, using [opensearch.pluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip), you dont need to have all this custom logic from the [PR](https://github.com/opensearch-project/index-management/pull/327), I would suggest to go with `opensearch.pluginzip`.

**Comment by prudhvigodithi** [comment]
Hey @downsrob and @ylwu-amzn, is it worth to now explore the pulling the zips from maven and removing the checking in files from src/test/resources/?
@dblock @bbarani

**Comment by downsrob** [comment]
@prudhvigodithi We have already converted to pulling the zips from maven and do not have any checked in zips in src/test/resources. That was tracked in this issue https://github.com/opensearch-project/index-management/issues/348 I believe. 
My understanding is that this issue is used for tracking the progress of allowing integration tests to run against dependencies of different versions, which is why it is still open despite no longer using checked in zips

**Comment by prudhvigodithi** [comment]
Got it thanks for the update @downsrob.

**Comment by prudhvigodithi** [comment]
Hey Starting with release 2.1.0, we now have plugin zips in [maven repo](https://repo1.maven.org/maven2/org/opensearch/plugin/)
We should be good to remove the checked in zips from repo from 2.x branches.
https://github.com/opensearch-project/opensearch-build/issues/1916#issuecomment-1179276885
Thank you

**Comment by downsrob** [comment]
@prudhvigodithi we do not have any checked in zips in the 2.x branches

**Comment by prudhvigodithi** [comment]
Thanks @downsrob, 
So can we expect to close this issue once PR: https://github.com/opensearch-project/index-management/pull/403 merged.
Thank you

**Comment by bbarani** [comment]
Can we close this issue as we have merged since https://github.com/opensearch-project/index-management/pull/403 has been merged now?

**Comment by prudhvigodithi** [comment]
Hey @downsrob just checking back again, if we can close this issue.
Thank you 
@bbarani @CEHENKLE
