### ISSUE TITLE
[PROPOSAL] Update MAINTAINERS.md

### ISSUE THREAD

**Issue by dblock** [opensearch-project/index-management#1230]
**Is your feature request related to a problem?**

Eyeballing the [metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/f1ad21c0-e323-11ee-9a74-07cd3b4ff414?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-6M,to:now))&_a=(description:'OpenSearch%20Ops%20Metrics',filters:!(('$state':(store:appState),meta:(alias:!n,controlledBy:'1710545443987',disabled:!f,index:efe46950-e31b-11ee-9a74-07cd3b4ff414,key:repository.keyword,negate:!f,params:(query:index-management),type:phrase),query:(match_phrase:(repository.keyword:index-management)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!t,title:'OpenSearch%20Ops%20Metrics',viewMode:view)) and the contents of https://github.com/opensearch-project/index-management/blob/main/MAINTAINERS.md a number of folks have not been active for a while. 

**What solution would you like?**

Move those who are no longer actively maintaining this repo to Emeritus.

Please comment if you're still actively maintaining this repo, and I can move the rest to Emeritus in 1 PR.

**Comment by vikasvb90** [comment]
Actively Maintaining!

**Comment by AWSHurneyt** [comment]
I am not actively maintaining this plugin, or the ISM dashboards plugin.

**Comment by amsiglan** [comment]
I am not actively maintaining this plugin, or the ISM dashboards plugin.

**Comment by lezzago** [comment]
I am not actively maintaining this plugin, or the ISM dashboards plugin.

**Comment by sbcd90** [comment]
I am not actively maintaining this plugin, or the ISM dashboards plugin.

**Comment by getsaurabh02** [comment]
Here is the data from last 6 months for contributions (PR + Issues)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sisurab/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sisurab/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


user_login.keyword:   Descending | GitHub contributions ( Issues + pull   requests )
-- | --
harshitakaushik-dev | 6
sarthakaggarwal97 | 6
bowenlan-amzn | 4
cwperks | 3
DarshitChanpura | 2
r1walz | 2
aggarwalShivani | 1
dblock | 1
ikibo | 1
mohitamg | 1
nisgoel-amazon | 1
rayshrey | 1
skumarp7 | 1
soosinha | 1
varun-lodaya | 1
vikasvb90 | 1



</body>

</html>


![Screenshot 2024-08-20 at 9 30 55 AM](https://github.com/user-attachments/assets/aa785149-42eb-4972-bd29-2a722cb16ed3)

**Comment by xluo-aws** [comment]
Please remove me from the list. Thanks

**Comment by praveensameneni** [comment]
I am not actively supporting Index Management. Please move to emeritus

**Comment by getsaurabh02** [comment]
I am not actively maintaining  Index Management, other than admin, release and generic triage tasks. Thanks

**Comment by jowg-amazon** [comment]
I am not actively maintaining this plugin, or the ISM dashboards plugin.

**Comment by r1walz** [comment]
Hi, @dblock. Vacationing till end of sept. I'll continue to maintain ISM. But, won't be sparing time on ISM Dashboards Plugin.

**Comment by bowenlan-amzn** [comment]
I'm still maintaining. Thanks @dblock.

**Comment by Hailong-am** [comment]
I'm still maintaining.

**Comment by eirsep** [comment]
I am not maintaining ISM or ISM dashbaords plugin actively

**Comment by gaobinlong** [comment]
I'm not actively maintaining the ISM and ISM dashboards plugin, please move me to the emeritus, thanks!
