### ISSUE TITLE
Meta issue for all new feature requests

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/index-management#143]
One place for all new feature requested:

## Index State Management

- Provide a way to define customized `index_creation_time` to be used by transition condition check. 
  - #104 
  - #65 
- Enhance snapshot action
  - #55 
  - #56 
  - #127 
- Shrink action
  - #40 
- Single ISM action for change any index setting.
  - #60 
  -  #67 
  - #135 
- Alias action
  - #35 

## Rollup

- Scriptable target index
  - #61 
- Support more aggregation type
  - #57 
  - #53 
  - #52

**Comment by dbbaughe** [comment]
Do we need this? 🤔
Tags + Filtering does the same thing

**Comment by bowenlan-amzn** [comment]
Close in favor of https://github.com/opensearch-project/index-management/projects/1
