### ISSUE TITLE
Continuous mode in transforms

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/index-management#152]
Even though transforms support a schedule, one can use this schedule to run the job only once. 
Need to support running the job in a continuous mode based on a schedule where new data added to the source indices are transformed in newer runs of transform job

**Comment by doomma** [comment]
@thalurur , would you have any inputs now on a ETA/plan for this enhancement?

**Comment by JeffBolle** [comment]
This should be clarified in the documentation until this issue is resolved.  The UI and documentation lead users (like me) to believe that our transforms should be running continuously.

**Comment by edwarmatoro** [comment]
Hi guys, do you know which version of OpenSearch is this bug fixed? I'm currently using v 1.1.0 and it has the bug; then I moved to 1.1.3 and still, the transform jobs are disabled once they run from the first time.

**Comment by edwarmatoro** [comment]
In case someone else face the same issue, it is resolved. You just need to add the parameter "continuous" : true.
