### ISSUE TITLE
[BUG] Cannot remove policy from read_only indices

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/index-management#171]
**Describe the bug**
Can manage indices that are read_only or has read_only_allow_delete blocks or make the index read_only as part of the policy. 
But once a read_only index is managed it cannot be unmanaged/policy cannot be removed from it because of failure to update auto_manage index settings to the index.

**Expected behavior**
Remove policies from read_only indices

**Comment by louzadod** [comment]
I could reproduce this bug with OS 1.1.0

**Comment by dbbaughe** [comment]
Looks like fix was released in 1.2 release, closing
