### ISSUE TITLE
[BUG] - No next page / more results button for data series indexes

### ISSUE THREAD

**Issue by camAtGitHub** [opensearch-project/index-management#178]
**Describe the bug**
No next page button / bad default filter applied for data series index types.

When using lots of aliased **datastream** indexes there is no next page on the managed indicies.
We have 160 backend indexes and about 15 aliases for them. They have names like linux, ldap, testing, win-events etc etc  

On the 'Managed Indices' page `/app/opensearch_index_management_dashboards#/managed-indices`
I would enable 'show data stream indices' and what is shown is a mix of testing indexes and a handful of others.   

Now if I change rows per page to 50 it will show only 20 indexes - a mix of testing and a handful of others and no page 2,3,4 etc button/hyperlink.  

In fact if I type in the filter/search bar a letter than spans like 's' then maximum results that get returned is 20. Rows = 50 - still 20 results and no page 2,3,4 etc button/hyperlink. (I have 157 indexes with the letter 's').

If I select a data stream from the drop down filter (next to show data stream indices slider) once again max results is 20. 

**To Reproduce**
1. Create a **data stream** index and template (template below)
2. Rollover data store 25-50+ times
3. Observe the limits imposed

**Expected behavior**
Show all indicies.

**Plugins**
default opensearch docker image 1.1.0

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 v21H1
Firefox v93.0

**Additional context**
Index Template: 
```
{
  "index_patterns": [
    "testing-*"
  ],
  "template": {
    "settings": {
      "plugins.index_state_management.rollover_alias": "testing"
    },
    "aliases": {
      "testing": {}
    }
  },
  "priority": 10,
  "data_stream": {
    "hidden": false,
    "timestamp_field": {
      "name": "@timestamp"
    }
  },
  "composed_of": [
    "field_mappings"
  ],
  "version": 1
}
```

**Comment by thalurur** [comment]
Hi,

This is an UI only bug and have recently pushed a fix to correct this behavior. The fix will be included in our next release https://github.com/opensearch-project/index-management-dashboards-plugin/pull/113
