### ISSUE TITLE
[BUG] Transforms indexing converting date fields to long

### ISSUE THREAD

**Issue by thalurur** [opensearch-project/index-management#202]
**Describe the bug**
Transform job is indexing the data as long instead of date field if grouping by a date field is selected

**Expected Behavior**
* Transform persist the mapping type of the index seen in source data in target indices

**Comment by victor-kyriazakos** [comment]
Hi @thalurur, are there any updates on this bug? We are facing the same issue. Are there any alternative ways to create transform jobs that will maintain the date field as expected?

**Comment by victor-kyriazakos** [comment]
Also, to add to this bug description, if we group by other terms and aggregate date as [min, max] then the field gets converted to "float", which is again unusable.
Finally, the PUT /<index>/_mappings API doesn't allow us to convert said long/float fields to date.

**Comment by tanqiuliu** [comment]
@xavier-isecurity  You can unblock yourself for now by defining the mappings of the target index beforehand. In the transform job you can specify `target_field` of the date histogram aggregation. As long as the index template has mappings specifies that field as `date`, the transformed index will follow that mapping

**Comment by xavier-isecurity** [comment]
> @xavier-isecurity You can unblock yourself for now by defining the mappings of the target index beforehand. In the transform job you can specify `target_field` of the date histogram aggregation. As long as the index template has mappings specifies that field as `date`, the transformed index will follow that mapping

Great to know! Thanks! I will test that soon as I have time.

**Comment by eirsep** [comment]
https://github.com/opensearch-project/index-management/pull/622
