### ISSUE TITLE
Add max_primary_shard_size as a rollover action in State Management Policy

### ISSUE THREAD

**Issue by Kevc1** [opensearch-project/index-management#213]
**Is your feature request related to a problem? Please describe.**
We need a way to rollover our indices if the shard size is >50gb as recommended by AWS.  This option exists in Elasticsearch and would be very beneficial to have available in Opensearch.

**Describe the solution you'd like**
Would like to have this option available in an ISM Policy, such as belwo:
                "name": "hot",
                "actions": [
                    {
                        "rollover": {
                            "min_size": "90gb",
                            "min_index_age": "7d",
                            "max_primary_shard_size" : "50gb"

                        }
                     },
                  ]

**Describe alternatives you've considered**

**Additional context**

**Comment by dbbaughe** [comment]
@Kevc1 

What is the expectation in terms of evaluating the condition to true:
* When at least one of the primary shards is > 50GB
* When the majority of primary shards are > 50GB
* When all of the primary shards are > 50GB

I'm guessing it's the first one.. but do you see value in the others at all?

**Comment by Kevc1** [comment]
I was initially thinking the second one but if any shard is going above the limit we probably want to rollover, so #1 would probebly be the safest.

**Comment by dbbaughe** [comment]
@Kevc1, Yes, the second and third one could end up with a hot shards issue where a lot of data is written to specific shards if using something like custom routing, perhaps before the rollover condition is met you have some shards that are already hundreds of GB or more.

**Comment by dbbaughe** [comment]
Merged into main, will go out in the next release (1.3).
