### ISSUE TITLE
How to push logs with weekly/monthly index instead of daily index.

### ISSUE THREAD

**Issue by jije-r** [opensearch-project/index-management#243]
**Is your feature request related to a problem? Please describe.**
Currently testing with aws-elasticsearch-plugin, seems some feature is not supported natively for weekly and monthly data management. Is there any other alternative plugin available for pushing logs from fluentd to aws opensearch

**Describe the solution you'd like**
an alternative plugin with weekly index management 

**Describe alternatives you've considered**

**Additional context**

**Comment by bowenlan-amzn** [comment]
Suggest to check [the cron transition condition](https://opensearch.org/docs/latest/im-plugin/ism/policies/#transitions) of ISM policy to see if you can use a weekly/monthly cron schedule to do your index management.
