### ISSUE TITLE
Need to be able to collect execution metrics

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#26]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dbbaughe](https://github.com/dbbaughe)**
_Tuesday Jul 23, 2019 at 22:51 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/39_

----

https://github.com/opendistro-for-elasticsearch/job-scheduler/issues/6

**Comment by bowenlan-amzn** [comment]
Close in favor of #31
