### ISSUE TITLE
[BUG] Failed concurrent creates of ISM policies should return http 409

### ISSUE THREAD

**Issue by phillbaker** [opensearch-project/index-management#260]
**Describe the bug**

When creating multiple policies on a fresh AWS OpenSearch cluster, it's likely to hit the following error:

```
elastic: Error 400 (Bad Request): index [.opendistro-ism-config/4pNn5XhHT3SwvIerntYi-A] already exists [type=resource_already_exists_exception]
```

Also see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/226

**To Reproduce**
Steps to reproduce the behavior: This is easy to do with a terraform provider but could also be scripted.
1. Spin up a new cluster
2. create multiple policies in parallel:
```
curl -X PUT -H 'Content-type: application/json' -d '{"policy":{"default_state":"hot","description":"Rotate index when the size of the index is too big.","ism_template":{"index_patterns":["logs*"],"priority":1000},"states":[{"actions":[{"rollover":{"min_index_age":"7d","min_size":"150gb"}}],"name":"hot","transitions":[{"conditions":{"min_index_age":"14d"},"state_name":"warm"}]},{"actions":[{"retry":{"count":5,"delay":"1h"},"warm_migration":{}}],"name":"warm","transitions":[{"conditions":{"min_index_age":"21d"},"state_name":"delete"}]},{"actions":[{"delete":{}}],"name":"delete"}]}}' localhost:9200/_plugins/_ism/policies/policy_1 & 
curl -X PUT -H 'Content-type: application/json' -d '{"policy":{"default_state":"hot","description":"For logs-rejected index. Smaller size and time to live index","ism_template":{"index_patterns":["logs-rejected*"],"priority":2000},"states":[{"actions":[{"rollover":{"min_index_age":"1d","min_size":"150gb"}}],"name":"hot","transitions":[{"conditions":{"min_index_age":"3d"},"state_name":"delete"}]},{"actions":[{"delete":{}}],"name":"delete"}]}}' localhost:9200/_plugins/_ism/policies/policy_2 & 
```

**Expected behavior**
Instead of a http 400, the specific error code http 409 should be returned, indicating a cluster concurrency issue instead of a request format issue.

**Plugins**
N/a

**Screenshots**
N/a

**Desktop (please complete the following information):**
N/A

**Additional context**
I believe this code could catch a `import org.opensearch.ResourceAlreadyExistsException` exception and return the specific error code: https://github.com/opensearch-project/index-management/blob/809b3c6abc6c079b48297771372a6c11d2ba7ab0/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/transport/action/indexpolicy/TransportIndexPolicyAction.kt#L94-L101

Similar to https://github.com/opensearch-project/security/issues/1402 and https://github.com/opensearch-project/security/issues/1095

**Comment by khushbr** [comment]
I will start looking into this issue.
