### ISSUE TITLE
[BUG] Existing indices are not assigned new ISM Policies

### ISSUE THREAD

**Issue by fgendc** [opensearch-project/index-management#264]
**Describe the bug**
Adding an ISM policy with an index pattern doesn't assign existing indices to the policy. 
According to the [documentation here](https://opensearch.org/docs/latest/im-plugin/ism/index/#visual-editor) states in point 6 that's not the expected behavior.

**To Reproduce**
1. Create index 'default-1'
`curl -XPUT http://localhost:9200/default-1 -d '{
  "settings": {
    "index": {
      "number_of_shards": 2,
      "number_of_replicas": 1
    }
  },
  "mappings": {
    "properties": {
      "age": {
        "type": "integer"
      }
    }
  },
  "aliases": {
    "sample-alias1": {}
  }
}' -H "Content-Type: application/json"`
2. On Dashboards, create new ISM Policy with ISM template and index_pattern "default-*"
3. Index is not assigned the Policy and doesn't appear in the Managed Index section in Dashboards.
4. Create index 'default-2'
`curl -XPUT http://localhost:9200/default-2 -d '{
  "settings": {
    "index": {
      "number_of_shards": 2,
      "number_of_replicas": 1
    }
  },
  "mappings": {
    "properties": {
      "age": {
        "type": "integer"
      }
    }
  },
  "aliases": {
    "sample-alias1": {}
  }
}' -H "Content-Type: application/json"`
5. default-1 isn't assigned the policy, but default-2 has it.

**Expected behavior**
default-1 index matches the pattern defined in the ISM template section of the policy and should be assigned the policy after creating it.

**Plugins**

- opensearch-alerting
- opensearch-anomaly-detection
- opensearch-asynchronous-search
- opensearch-cross-cluster-replication
- opensearch-index-management
- opensearch-job-scheduler
- opensearch-knn
- opensearch-observability
- opensearch-performance-analyzer
- opensearch-reports-scheduler
- opensearch-security
- opensearch-sql
- repository-s3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.2

**Additional context**
Installed on Kubernetes using Helm for both OpenSearch (1.2.4) and OpenSearch Dashboards (1.2.0), with Security Plugin disabled.

**Comment by bowenlan-amzn** [comment]
ISM template only works for indices created afterwards.

But you can hack it to manage earlier created index by changing the `last_updated_time` of `ism_template` to an earlier time epoch.

```
ism_template: {
  index_patterns: ...
  priority: ...
  last_updated_time: <earlier time epoch>
}
```

**Comment by fedemengo** [comment]
@bowenlan-amzn it doesn't seem to be working on OS v2
