### ISSUE TITLE
Improve Add Policy API by using transport action instead of timeout

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#28]
<a href="https://github.com/qreshi"><img src="https://avatars.githubusercontent.com/u/47198598?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [qreshi](https://github.com/qreshi)**
_Wednesday Jul 24, 2019 at 00:32 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/42_

----

The initial implementation of the Add Policy API had a concerning case where two requests to add policy could overwrite each other. The concern was brought up [here](https://github.com/opendistro-for-elasticsearch/index-management/pull/31#discussion_r305964553).

As a temporary fix, a timeout of 30 seconds was added to the Add Policy API action. As a more permanent fix, a transport action should perform the logic of iterating through the cluster state and updating the indices' settings on the master node itself, preventing requests to add policy both returning ```200``` status and one overwriting the other.

**Comment by bowenlan-amzn** [comment]
We have removed policyId usage when doing Add Policy API call. We now directly indexed managed jobs document into config index. So this problem should not exist anymore.
