### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/index-management#285]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x until further notice to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.

**Describe the solution you'd like**
Replace the  terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment and internal variable name.
- Deprecate REST API (request parameter) that contains "master" and provide alternative inclusive usage:
deprecate parameter "master_timeout" and add new parameter "cluster_manager_timeout" in [RestExplainAction](https://github.com/opensearch-project/index-management/blob/1.3.1.0/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestExplainAction.kt#L80) (updated after [the below comment](https://github.com/opensearch-project/index-management/issues/285#issuecomment-1101838955))

When being compatible with OpenSearch 3.0:
- Replace "master" in the reference to OpenSearch Java API
(most of the new APIs are available in version 2.2, except `AcknowledgedResponse`) 
  - [ ] clusterStateRequest.masterNodeTimeout() -> clusterManagerNodeTimeout()
  - [ ] import org.opensearch.action.support.master.MasterNodeRequest -> import org.opensearch.action.support.clustermanager.ClusterManagerNodeRequest
  - [ ] import org.opensearch.action.support.master.TransportMasterNodeAction -> import org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction
  - [ ] import org.opensearch.action.support.master.AcknowledgedResponse -> import org.opensearch.action.support.clustermanager.AcknowledgedResponse (will be available in version 3.0)

**Describe alternatives you've considered**
None.

**Additional context**

Related issues: 
- https://github.com/opensearch-project/documentation-website/issues/450 Describes the newly added alternative OpenSearch REST API / Setting for all the non-inclusive usages.
- https://github.com/opensearch-project/OpenSearch/issues/1684

Note about the API request parameter `master_timeout`:
From my understanding, the parameter `master_timeout` is used in "Explain Index" API of the plugin, and it's independent with OpenSearch (core), so you could deal with it alone.
I suggest to deprecate the request parameter `master_timeout`, and add a new request parameter `cluster_manager_timeout`. Then remove the support of parameter `master_timeout` in the future.

How OpenSearch deal with the API request parameter `master_timeout`:
In OpenSearch, the parameter `master_timeout` is deprecated and will be replaced by parameter `cluster_manager_timeout`.
The code change was tracked in the issue https://github.com/opensearch-project/OpenSearch/issues/2511

The timeline for deprecating the parameter `master_timeout` is special in OpenSearch (core):
1. In version 2.0: new parameter `cluster_manager_timeout` is added, while no warning for using `master_timeout`.
2. In version 3.0: deprecation warning will be emitted if using the parameter `master_timeout`.
3. In version 4.0: the support of `master_timeout` will be removed.

Technically it is fine to keep using the parameter `master_timeout` when being compatible with OpenSearch 2.0, but deprecation warning will be shown in 3.0 .

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by CEHENKLE** [comment]
@opensearch-project/index-management Can you please verify @dblock's question so we can remove the 2.0 label?  Thanks

**Comment by bowenlan-amzn** [comment]
@tlfeng helps pointing out the `master_timeout` API parameter usage in our repo.
e.g.
https://github.com/opensearch-project/index-management/blob/2d3fd977168063f1e8ecc29018e897e629352392/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/resthandler/RestExplainAction.kt#L80

And the related issue: https://github.com/opensearch-project/OpenSearch/issues/2928
We will follow the same method as in the above issue to deal with this parameter

**Comment by anasalkouz** [comment]
Java APIs completed and released on 2.2 except for AcknowledgedResponse.
@bowenlan-amzn Could you please complete the remaining part from your end? let's target 2.3 for all usages except for AcknowledgedResponse (there will be separate issue to track it).
