### ISSUE TITLE
[BUG] Action timed out ; retry not consumed at AWS Ultrawarm migration #465

### ISSUE THREAD

**Issue by thom-vend** [opensearch-project/index-management#315]
### Bug description
On a flow hot>warm>delete some ism policy stop managing **SOME** indexes at the warm migration.
So they are never moving to the next action to delete them and fill my ultrawarm node disk space.

Seems very close to: https://github.com/opendistro-for-elasticsearch/index-management/issues/130
But @dbbaughe merge a fix and backport it to the version available on AWS?

### Other plugins installed / version used
SAML auth
using the AWS setup of OpenSearch 1.1
Service software version: R20211203-P5
Using AWS UltraWarm nodes
Index are created by date and will start their (ultra) warm migration at the same time. (I feel that important)

### Expected behavior
ISM should retry and consume the configured retries?

#### Example of policie
<details><summary>Click here to display the policy</summary>

```json
{
  "_id": "logstash-apptest1",
  "_version": 15,
  "_seq_no": 104277,
  "_primary_term": 1,
  "policy": {
    "policy_id": "logstash-apptest1",
    "description": "hot-warm-delete-generated-for-logstash-apptest1",
    "last_updated_time": 1648180619170,
    "schema_version": 12,
    "error_notification": null,
    "default_state": "hot",
    "states": [
      {
        "name": "hot",
        "actions": [
          {
            "index_priority": {
              "priority": 100
            }
          }
        ],
        "transitions": [
          {
            "state_name": "warm",
            "conditions": {
              "min_index_age": "6d"
            }
          }
        ]
      },
      {
        "name": "warm",
        "actions": [
          {
            "timeout": "4h",
            "retry": {
              "count": 8,
              "backoff": "exponential",
              "delay": "1h"
            },
            "warm_migration": {}
          }
        ],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "7d"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [
          {
            "delete": {}
          }
        ],
        "transitions": []
      }
    ],
    "ism_template": [
      {
        "index_patterns": [
          "logstash-apptest1*"
        ],
        "priority": 100,
        "last_updated_time": 1648180619170
      }
    ]
  }
}
```
</details>

#### Index status
from `/_plugins/_ism/explain/logstash-apptest1-2022.03.2`
<details><summary>Click here to display the index status (explain)</summary>

```json
{
  "logstash-apptest1-2022.03.21": {
    "index.plugins.index_state_management.policy_id": "logstash-apptest1",
    "index.opendistro.index_state_management.policy_id": "logstash-apptest1",
    "index": "logstash-apptest1-2022.03.21",
    "index_uuid": "wWf7Xm44R5GK5A_45S43xA",
    "policy_id": "logstash-apptest1",
    "policy_seq_no": -2,
    "policy_primary_term": 0,
    "index_creation_date": 1647820802609,
    "state": {
      "name": "warm",
      "start_time": 1648255548990
    },
    "action": {
      "name": "warm_migration",
      "start_time": 1648255548990,
      "index": 0,
      "failed": true,
      "consumed_retries": 0,
      "last_retry_time": 0
    },
    "step": {
      "name": "wait_for_warm_migration",
      "start_time": 1648257352295,
      "step_status": "condition_not_met"
    },
    "retry_info": {
      "failed": false,
      "consumed_retries": 0
    },
    "info": {
      "message": "Action timed out"
    },
    "enabled": false
  },
  "total_managed_indices": 1
}
```
</details>

Action: failed
retry: not failed and not consumed 🤔 

### No others logs
- searched for those index name in Opensearch (es) application logs : nothing for them.

### Workaround
I can click in Opensearch dashboard to retry the policy from the warm state.
or wrote a script to call the api to do the same

### Thoughts
Is it related to the nature of the ultrawarm and the migration there combined with all index migrating at the same time?

Thanks!

**Comment by thom-vend** [comment]
Opened here too: https://github.com/opendistro-for-elasticsearch/index-management/issues/465 Which one should I close? 😕

**Comment by thom-vend** [comment]
_AWS support advise us to remove the timeout, currently under observation 😊_

**Comment by dbbaughe** [comment]
Reposting:

I think there's a disconnect here and a poorly named option.
The timeout does not time out a single individual execution which is then retryable based on the configured retries.
It is a global timeout, meaning if the action was not able to successfully execute through all of its attempts within this configured timeout, then the action will be permanently failed and require someone to manually call the retry API on it after figuring out why it's not successful. So your example is saying if the warm migration does not successfully complete within 4 hours (regardless of how many attempts have been attempted, even if there are more to consume still) then it will enter a failed state.

**Comment by dbbaughe** [comment]
Will close this, feel free to open a discussion on the forums if you have more questions.
