### ISSUE TITLE
Rollup - Allow query_string queries against rollup data

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/index-management#320]
https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#query-string

We need to confirm this is doable and then write the translation logic to take in the query string and rewrite it to the internal data format.

**Comment by praveensameneni** [comment]
Meta issue - https://github.com/opensearch-project/index-management/issues/408

**Comment by setiah** [comment]
@Angie-Zhang and I were discussing about the potential use cases here and one potential use case that came up where `query_string` based queries could be useful with rollup - for example, a user ingesting cpu usage data for every node in a distributed system at 10s frequency. They rollup the data to 5 min granularity in a rollup index. Now they want to search the data based on node-Id field. They could use query_string to specify the node-id and search the rollup data for a particular node.

**Comment by Angie-Zhang** [comment]
@setiah and I realize that our _search endpoint also supports using "simple_query_string". It lets advanced users specify many arguments directly in the query string. The query discards any invalid portions of the query string. We can support simple_query_string for rollup search, which is consist with the usage of _search endpoint.

**Comment by downsrob** [comment]
An initial PR has been opened to address this, but at this point in time it only supports searching across all fields for specific values. The user may use boolean logic in the query string, but may not specify field names such as "fruit_type:apple", as the rollups backend renames fields and the interceptor needs to add logic for translating these field names. 
It would be easy to translate the default field, but translating fields inside of the query string would require writing a string parser and will take a deep dive into the query string syntax. One simple solution would be if we could leverage the [Lucene query parser](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) which is being used under the hood to convert query string queries to bool queries anyways. We already have support for intercepting and modifying bool queries for rollups. It may not be possible to make use of this parser though, more investigation is needed.

**Comment by deshsidd** [comment]
PR: https://github.com/opensearch-project/index-management/pull/616
DOC issue: https://github.com/opensearch-project/documentation-website/issues/2341
