### ISSUE TITLE
Allow rollup searches to multiple rollup indices if they have the same rollup

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/index-management#321]
We currently do not allow a rollup search to search more than one index.

We should relax the constraint such that you can search multiple rollup indices if the rollups are the same for when we support a single rollup writing to multiple target indices.

We need to make sure that either the rollup indices have a single rollup that are all the same or they will also resolve to the same rollup when searched.

**Comment by praveensameneni** [comment]
Meta issue - https://github.com/opensearch-project/index-management/issues/408

**Comment by setiah** [comment]
Had a quick chat with @downsrob. This enhancement seems like a post-requisite for https://github.com/opensearch-project/index-management/issues/61. After we have rolled up data going to multiple target indices, we might need the ability to search across multiple indices with rollup id

**Comment by Angie-Zhang** [comment]
@setiah 
Checked the discuss on dynamic target index. Considering the search ability, I think we need some fixed pattern/prefix for dynamic target indices from the same policy, so user can search multiple target indices which comes from the same policy.

**Comment by downsrob** [comment]
This change has been merged, but without any added tests. We need to add tests for this feature before closing the issue.
