### ISSUE TITLE
[BUG] ISM template should compatible with index template usage

### ISSUE THREAD

**Issue by xiaoyuan0821** [opensearch-project/index-management#357]
**What is the bug?**
After upgrade our ES from 7.6 to 7.10, we found using index template to set policyID to manage index automatically is not work anymore, maybe we should compatible with  index template usage after add ISM template?

**How can one reproduce the bug?**
1. create a new policy with name `hot_cold_policy` but no `ism_template` field specified.
2. create index template 
```
PUT _template/template_test
{
  "index_patterns": "data*",
  "settings": {
    "opendistro.index_state_management.policy_id": "hot_cold_policy"
  }
}
```
4. create new index with name `data123`

**What is the expected behavior?**
Index `data123` is managed by ISM

**Comment by downsrob** [comment]
Looks to me like support for applying policies by the policy_id index setting was removed with this PR https://github.com/opendistro-for-elasticsearch/index-management/pull/357
It looks like that behavior was intentionally removed, @bowenlan-amzn I see you authored the PR, do you have any more information on why this behavior needed to be removed?

**Comment by bowenlan-amzn** [comment]
This is a breaking change. In 7.10, `policy_id` setting is not functional anymore and you will need to use ISM template instead: https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/policies/#sample-policy-with-ism-template

**Comment by downsrob** [comment]
Closing this issue as it was an intended breaking change. Feel free to open again if you have any other questions.
