### ISSUE TITLE
Query Action

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#36]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dbbaughe](https://github.com/dbbaughe)**
_Tuesday Feb 11, 2020 at 19:06 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/149_

----

During the community meeting, someone asked if it was possible to have an action to modify the data in the index by using a query to delete documents over a certain threshold etc.

Since this involves accessing data it has more security implications that would need to be thought out.

Will use this issue to track it + see if other people are interested.

**Comment by aditjind** [comment]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbbaughe](https://github.com/dbbaughe)**
_Monday Oct 05, 2020 at 21:57 GMT_

----

Another ask is to use this for prewarming data by loading it in the cache -- with an option to have it be fire and forget; meaning don't wait on a response and just assume it was successful.

**Comment by bowenlan-amzn** [comment]
Track in https://github.com/opensearch-project/index-management/projects/1#card-71473393
