### ISSUE TITLE
[BUG] ISM Plugin - Policy not apply to all concerned indices

### ISSUE THREAD

**Issue by sevenval-admins** [opensearch-project/index-management#364]
**Describe the bug**

Hi everybody, I don´t know if this is a bug or not, but this is my problem:
I have an index_patter "my-index-*"
I have created a Policy in order to delete indices older than 2 weeks:

```
{
    "policy_id": "my-policy",
    "description": "Cluster Policy in oder to delete indexes that are older than two weeks",
    "last_updated_time": 1652361748577,
    "schema_version": 13,
    "error_notification": null,
    "default_state": "Running",
    "states": [
        {
            "name": "Running",
            "actions": [],
            "transitions": [
                {
                    "state_name": "Delete",
                    "conditions": {
                        "min_index_age": "14d"
                    }
                }
            ]
        },
        {
            "name": "Delete",
            "actions": [
                {
                    "retry": {
                        "count": 3,
                        "backoff": "exponential",
                        "delay": "1m"
                    },
                    "delete": {}
                }
            ],
            "transitions": []
        }
    ],
    "ism_template": [
        {
            "index_patterns": [
                "my-index-*"
            ],
            "priority": 100,
            "last_updated_time": 1652348329009
        }
    ]
}
```
Now let´s say I have 10 indices:

```
my-index-namespace01-2020-05-12
my-index-namespace02-2020-05-12
my-index-namespace03-2020-05-12
my-index-namespace04-2020-05-12
my-index-namespace05-2020-05-12
my-index-namespace06-2020-05-12
my-index-namespace07-2020-05-12
my-index-namespace08-2020-05-12
my-index-namespace09-2020-05-12
my-index-namespace10-2020-05-12
```

how can be that under Managed Indices just the first two are shown as managed by the policy?

**Expected behavior**
All the indices under "my-index-*" should be managed by the policy

**OpenSearch Version**
1.3.2, Helm Chart v1.11.1

**Dashboards Version**
1.3.2, Helm Chart v1.5.1

Thanks in advance to everyone who will have a look into it.

**Comment by downsrob** [comment]
Hello @sevenval-admins, did you create the policy after the indices or the indices after the policy? If the policy was created after, then it will not be applied to the older indices.

**Comment by downsrob** [comment]
If what you described is not related to the above, would you be able to provide some more information on how to reproduce it? I tried with 1.3.2 OpenSearch and when the indices were created after the policy, the policy was always applied successfully. Was there anything else special about those indices?

**Comment by sevenval-admins** [comment]
The Policy was created after, problem is solved, thanks to all you guys.

**Comment by cuongvc1** [comment]
> The Policy was created after, problem is solved, thanks to all you guys.

Hi sir
I have same yout poblem. How did you do

**Comment by anshad14** [comment]
@downsrob So I need to apply the policy manually to the older indices. Are there any other ways to apply the policy to all older indices?

**Comment by junandaip** [comment]
@downsrob please answer since there's no official opensearch curator
