### ISSUE TITLE
Performance: Look into moving ManagedIndexMetaData from cluster state into index

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#41]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dbbaughe](https://github.com/dbbaughe)**
_Friday Apr 24, 2020 at 16:15 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/207_

----

Every Managed Index job has its own lifecycle which includes updating the cluster state for executions.
Because the cluster state is applied sequentially in a single thread and needs acknowledgement from other nodes for each update once you start managing thousands of indices it becomes a bottleneck.

We have some workarounds to help with this (making steps idempotent, only updating cluster state if actual work will be done, increasing cluster state update timeout), but these are mostly just bandaids on the issue and while they might keep us afloat for a while, we're probably not going to hit the scale we want (10k+ managed indices on a cluster).

We should consider moving the ManagedIndexMetaData out of the cluster state and into the config index itself. This is non trivial mainly because of the automatic migration that needs to happen once someone uses an updated plugin from the old one. We'll need to do some extensive testing around this along with performance testing to see the impact.

**Comment by dbbaughe** [comment]
This was completed by https://github.com/opendistro-for-elasticsearch/index-management/pull/280
