### ISSUE TITLE
(Remote) Reindex Action

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#42]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dbbaughe](https://github.com/dbbaughe)**
_Friday May 08, 2020 at 01:53 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/220_

----

From Carl in RFC issue: I got feedback from a conversation today to add remote reindex as supported operation to move indexes to another cluster. To add to your list for consideration.

**Comment by aditjind** [comment]
<a href="https://github.com/psaiz"><img src="https://avatars.githubusercontent.com/u/12909623?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [psaiz](https://github.com/psaiz)**
_Wednesday May 19, 2021 at 11:05 GMT_

----

It would be nice to have the reindex in the same cluster as well (like curator does).

The use case I have in mind:
 * The producer creates big daily indices
 * After one week, the daily indices will be reindexed into monthly indices, to reduce the total number of indices and shards

**Comment by bowenlan-amzn** [comment]
Track in https://github.com/opensearch-project/index-management/projects/1#card-71473393
