### ISSUE TITLE
[BUG] datastream shrinking policy creates hidden indices ignored by ISM

### ISSUE THREAD

**Issue by lockwooddev** [opensearch-project/index-management#478]
**What is the bug?**
We created a shrink action in a policy for our datastreams to reduce the number of shards.

We start out with index `.ds-example-000001` and this one turns into `.ds-example-000001_shrunken`. The shrunken index is not part of the datastream after shrinking and treated as a hidden index. We can now no longer apply a retention policy specifically for these shrunken indices, because the ISM ignores them:

https://github.com/opensearch-project/index-management/blob/main/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt#L368

**How can one reproduce the bug?**

Create the datastream index template
```
PUT _index_template/example
```
```json
{
    "index_patterns": [
        "example"
    ],
    "data_stream": {},
    "priority": 100,
    "template": {
        "settings": {
            "number_of_shards": 2,
            "number_of_replicas": 1
        }
    }
}
```

Create the policy
```
PUT _plugins/_ism/policies/example-policy
```

```json
{
    "policy": {
        "policy_id": "example-policy",
        "description": "",
        "schema_version": 1,
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "rollover": {
                            "min_doc_count": "3"
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "cold"
                    }
                ]
            },
            {
                "name": "cold",
                "actions": [
                    {
                        "force_merge": {
                            "max_num_segments": 1
                        }
                    },
                    {
                        "shrink": {
                            "num_new_shards": 1,
                            "force_unsafe": false
                        }
                    },
                    {
                      "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "example*"
                ],
                "priority": 100
            }
        ]
    }
}
```

Create documents

```
POST example/_doc
```
```json
{
    "@timestamp": "2022-08-16T10:00:00.0",
    "@version": "1",
    "message": "example message 1"
}
```

```
POST example/_doc
```
```json
{
    "@timestamp": "2022-08-16T10:00:01.0",
    "@version": "1",
    "message": "example message 2"
}
```

```
POST example/_doc
```
```json
{
    "@timestamp": "2022-08-16T10:00:02.0",
    "@version": "1",
    "message": "example message 3"
}
```

```
POST example/_doc
```
```json
{
    "@timestamp": "2022-08-16T10:00:03.0",
    "@version": "1",
    "message": "example message 4"
}
```

Now we wait and after a while we have the following indices:

```
GET /_cat/indices/.*example*
```

```
green open .ds-example-000002          q0Pi8T2VRH6hJlconGvpnw 2 1 0 0   832b  416b
green open .ds-example-000001_shrunken zxeuCq8sSJuuQL0TCRPtCg 1 1 4 0 19.3kb 9.6kb
```

**What is the expected behavior?**

I would expect perhaps some more ability to change the future index name, remove the `.ds-` prefix.
An alternative would be to unhide the index after shrinking.

**What is your host/environment?**
 - Docker Deskstop 4.11.1
 - opensearchproject/opensearch:2.2.0

**Comment by bowenlan-amzn** [comment]
According to the [doc](https://opensearch.org/docs/latest/im-plugin/ism/policies/#shrink), can you try this to define a template to add a prefix to the shrunk index
```
"shrink": {
    "target_index_name_template": {
        "source": "shrunk_{{ctx.index}}"
    }
}
```

For why the shrunk index `.ds-example-000001_shrunken` is hidden after creation, I suspect it relates to the template you need for setting up data stream. The new shrunk index got matched by the data stream template.

**Comment by bowenlan-amzn** [comment]
Feel free to open if you have other idea

**Comment by shaigbdb** [comment]
Thanks @bowenlan-amzn , this has been helpful in better understanding the shrink operation.
Unfortunately the shrunken index is created with "index.hidden": "true" (tested in 2.17.1). This is unaffected by the template for the data stream.
The behavior is similar with the shrink API. The shrink API has a settings paramater that allows changing settings, but using this doesn't help with getting ISM to recognize the index.

The only workaround I currently see is to have a recurring script that applies the policies to new shrunken indices. This returns failures for the indices that already have a policy, but seems to succeed in updating the others.

POST _plugins/_ism/add/shrunk-*
{
  "policy_id": "..."
}





> According to the [doc](https://opensearch.org/docs/latest/im-plugin/ism/policies/#shrink), can you try this to define a template to add a prefix to the shrunk index
> 
> ```
> "shrink": {
>     "target_index_name_template": {
>         "source": "shrunk_{{ctx.index}}"
>     }
> }
> ```
> 
> Behind the scene, it's parsed by Mustache. I didn't find out Mustache can slice the string to remove `.ds`. But I confirmed that we can create an index with `.` in the middle.
> 
> For why the shrunk index `.ds-example-000001_shrunken` is hidden after creation, I suspect it relates to the template you need for setting up data stream. The new shrunk index got matched by the data stream template.
