### ISSUE TITLE
Missing rollover_alias in index setting

### ISSUE THREAD

**Issue by dipenpatel235** [opensearch-project/index-management#480]
**Describe the bug**
I have apply index rollover policy to transfer data hot node to warm node.

I am getting this info error and job status = Failed in managed indices.

![image](https://user-images.githubusercontent.com/8135097/186594611-09d24432-d119-48e2-8b9a-0cb301de49c1.png)

![image](https://user-images.githubusercontent.com/8135097/186594680-f561f381-fa9c-495f-b76d-2384d56643b4.png)

Thanks,
Dipen.

**Comment by bowenlan-amzn** [comment]
Please refer to our doc: https://opensearch.org/docs/latest/im-plugin/ism/policies/#sample-policy-with-ism-template-for-auto-rollover
