### ISSUE TITLE
Provide Restore action in Snapshot Management UI

### ISSUE THREAD

**Issue by setiah** [opensearch-project/index-management#495]
Users cannot restore the snapshots via the Snapshot Management pane in the Dashboards today. This ask is to add restore option support. 

* With this feature, users can restore their snapshots on the cluster via Dashboards UI
* Users can restore full or partial snapshots, all or some indices based on the options selected.
* Users can view the ongoing restore activities on the UI itself.
* Note: Restore activity history is out of scope as there is no backend API to support it today and the scope of this addition is limited to frontend. However this is something we would like to support in future.

Extension of https://github.com/opensearch-project/index-management/issues/280

**Comment by bowenlan-amzn** [comment]
Close in favor of the same task on frontend repo https://github.com/opensearch-project/index-management-dashboards-plugin/issues/243
