### ISSUE TITLE
Additional metrics | add percentiles to histogram aggregations (for numeric data).

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#52]
<a href="https://github.com/WassimDhib"><img src="https://avatars.githubusercontent.com/u/30473593?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [WassimDhib](https://github.com/WassimDhib)**
_Friday Dec 18, 2020 at 16:10 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/362_

----

**Is your feature request related to a problem? Please describe.**

When defining a rollup job, you can aggregate additional fields from the source index into the target index. Rollup supports the terms aggregation (for all field types) and histogram aggregation (for numeric fields) : min/max/sum/avg/value count

When doing application performance analysis, we always check higher percentiles of performance KPIs (server time, round trip time ...)

**Describe the solution you'd like**
Can you add percentiles to histogram aggregations (for numeric data).

**Comment by bowenlan-amzn** [comment]
Track in https://github.com/opensearch-project/index-management/projects/1#card-78384211
