### ISSUE TITLE
Rollup aggregate: add rate / positive rate

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#53]
<a href="https://github.com/ict-one-nl"><img src="https://avatars.githubusercontent.com/u/2643715?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ict-one-nl](https://github.com/ict-one-nl)**
_Sunday Dec 20, 2020 at 04:12 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/363_

----

**Is your feature request related to a problem? Please describe.**
A lot of iot devices use counter type measurements, think energy meters, snmp counters, etc. I want to roll up this data storing only the changes (with an option for only positive rates)

**Describe the solution you'd like**
Add rollup aggregate for counters with both normal rate and positive rate of change

**Describe alternatives you've considered**
Using max and then positive rate in kibana, but not ideal

**Additional context**

**Comment by bowenlan-amzn** [comment]
Track in https://github.com/opensearch-project/index-management/projects/1#card-78384211
