### ISSUE TITLE
Snapshot Lifecycle Management (SLM) and Index Lifecycle Management (ILM) 

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#55]
<a href="https://github.com/harishjadhav26"><img src="https://avatars.githubusercontent.com/u/57670076?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [harishjadhav26](https://github.com/harishjadhav26)**
_Thursday Nov 26, 2020 at 05:44 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/370_

----

Hello Team is there any feature to manage Snapshot Lifecycle Management (SLM) and Index Lifecycle Management (ILM) 
gui base like ELK stack basic license feature in open distro.
also have retention policy for both gui based.

![image](https://user-images.githubusercontent.com/57670076/100312703-000a0f00-2fd9-11eb-8421-25fc26e51b7a.png)
![image](https://user-images.githubusercontent.com/57670076/100312734-1748fc80-2fd9-11eb-9783-44565ba47e4c.png)

**Comment by felipehertwig** [comment]
I'm curious about this, did you learn or find any news about it? is it possible to use it in the OSS version?

**Comment by therealhanlin** [comment]
Just wanna check in here as there hasn't been any updates recently. 

I've been trying to find a way to snapshot the indices to a S3 bucket, and remove them after 6 months to a year. But havent found a way to do it unless I'm running a schedule job to trigger Opensearch to clean up the files.

**Comment by soolch** [comment]
In my wishlist as well.

**Comment by JathinSanghvi** [comment]
this would be useful for us too.

**Comment by ynuyasha** [comment]
great feature to have
