### ISSUE TITLE
snapshot policy should allow specifying indices

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#56]
<a href="https://github.com/wyllys66"><img src="https://avatars.githubusercontent.com/u/4163874?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wyllys66](https://github.com/wyllys66)**
_Monday Jan 11, 2021 at 22:50 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/382_

----

Currently, (release 1.12.0), it appears that we cannot specify what indexes to include in a snapshot when the snapshot is triggered by a policy. The policy action for "snapshot" only includes the repository and the name of the snapshot. It should allow for additional parameters related to snapshot operations.

**Comment by aditjind** [comment]
<a href="https://github.com/wyllys66"><img src="https://avatars.githubusercontent.com/u/4163874?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wyllys66](https://github.com/wyllys66)**
_Wednesday Jan 20, 2021 at 17:22 GMT_

----

While it is possible to create index_templates that assign a snapshot policy to a list of matching indices, the problem with that approach is that it results in a separate snapshot for each index.  It would be so much better if there was a single snapshot that included the matching indices.  This is pretty significant.

**Comment by aditjind** [comment]
<a href="https://github.com/lav-kush"><img src="https://avatars.githubusercontent.com/u/31899606?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lav-kush](https://github.com/lav-kush)**
_Tuesday May 25, 2021 at 15:18 GMT_

----

Currently, it appears that we cannot specify dynamic snapshot name in ISM policy. The policy action for "snapshot" only includes the repository and the static name of the snapshot, and it creates separate snapshot for each indices with name <snapshot-name>-<timestamp>.  It should allow to pass dynamic snapshot name say for each index something like ctx.index var as used in message template.

**Comment by ynuyasha** [comment]
I agree totally with this. Actually we still using script with curator to aggregate with some logic indexes in one daily snapshot. And we cannot migrate to ISM because a snapshot for every index create a proliferation inside a S3 repository and after that will be difficult to retrieve and manage all snapshots with snapshot api caused by slowness of response do to the high number of snapshots.

**Comment by bowenlan-amzn** [comment]
Please check snapshot management feature https://opensearch.org/docs/latest/opensearch/snapshots/snapshot-management/
