### ISSUE TITLE
Backport Windows support to 1.x branch

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/index-management#617]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/181, backport Windows support to 1.x branch.

- [ ] Passing CI for 1.x branch on Windows
- [ ] Documentation

If you are already have an issue tracking backport Windows CI to 1.x branch, please link here.

**Comment by bowenlan-amzn** [comment]
1.3 1.x branch already have windows enabled in test workflow
https://github.com/opensearch-project/index-management/blob/1.x/.github/workflows/test-and-build-workflow.yml#L23
https://github.com/opensearch-project/index-management/blob/1.3/.github/workflows/test-and-build-workflow.yml#L23
