### ISSUE TITLE
[BUG] Names don't adhere to plugin naming convention

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/index-management#620]
**What is the bug?**
As per https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#opensearch-plugins, the folder name needs to adhere to the naming convention

**What is the expected behavior?**
[Folder needs to be created and Include full plugin name in kebab case, e.g., plugins/opensearch-index-management](https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#folders)

**Do you have any additional context?**
Referred to here:
https://github.com/opensearch-project/opensearch-plugins/issues/174

**Comment by bowenlan-amzn** [comment]
We are using kebab case opensearch-index-management
