### ISSUE TITLE
[BUG] Tests are flakey

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#63]
<a href="https://github.com/thalurur"><img src="https://avatars.githubusercontent.com/u/6005951?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thalurur](https://github.com/thalurur)**
_Tuesday Apr 13, 2021 at 20:50 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/438_

----

**Describe the bug**
Tests are sometimes randomly failing either in single node or multi node runs

**Comment by thalurur** [comment]
https://github.com/opensearch-project/index-management/issues/90
