### ISSUE TITLE
Rollover on min_index_age clashes with Reindexing?

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#65]
<a href="https://github.com/activeperception"><img src="https://avatars.githubusercontent.com/u/6286377?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [activeperception](https://github.com/activeperception)**
_Friday Apr 23, 2021 at 14:59 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/442_

----

Hi, 

We've setup ISM to rollover/transition based on min_index_age but we realized that reindexing clashes with it. After reindexing the new index gets a new creation date and the policy running on min_index_age gets obviously delayed. 

Is there a workaround anyone can think of? AFAIK it's possible to override the creation date for an index in Elastic but not with Opendistro, maybe that would be enough to fix the issue.

Alternatively reindex could be changed to copy over, optionally, the original index metadata (creation time in this case).

Thanks for your help,
 Raffaele

**Comment by bowenlan-amzn** [comment]
Under https://github.com/opensearch-project/index-management/projects/1#card-78383842
