### ISSUE TITLE
total_shards_per_node setting action

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/index-management#67]
<a href="https://github.com/samehif"><img src="https://avatars.githubusercontent.com/u/18121371?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [samehif](https://github.com/samehif)**
_Tuesday May 04, 2021 at 11:56 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/index-management/issues/445_

----

how can i change the index total_shards_per_node setting using a policy?

**Comment by bowenlan-amzn** [comment]
Under https://github.com/opensearch-project/index-management/projects/1#card-78383721

**Comment by mosajjal** [comment]
Hi Team, does this feature exist? anyone got an example I can use :)
