### ISSUE TITLE
[BUG] Transform API should throw exception for unsupported aggregation type

### ISSUE THREAD

**Issue by Angie-Zhang** [opensearch-project/index-management#671]
**What is the bug?**
When creating transform jobs, even if the request format contains unsupported aggregation types, the transform API still returns 201 success.  After the transform job created, the job has Error Status.

**How can one reproduce the bug?**
In Dev Tools set a request to create a transform job:
```
PUT _plugins/_transform/bucket_script_test
{
  "transform": {
    "enabled": true,
    "continuous": true,
    "schedule": {
      "interval": {
        "period": 1,
        "unit": "Minutes"
      }
    },
    "description": "Sample transform job",
    "source_index": "transform_test_source",
    "target_index": "transform_test_target",
    "data_selection_query": {
      "match_all": {}
    },
    "page_size": 1,
    "groups": [
      {
        "terms": {
          "source_field": "price",
          "target_field": "original_price"
        }
      },
      {
        "terms": {
          "source_field": "discount",
          "target_field": "discount"
        }
      }
    ],
    "aggregations": {
       "final_price": {
        "bucket_script": {
            "buckets_path": {
                "p": "price",
                "d": "discount"
            },
            "script": "params.p * (1 - params.d)"
        }
    }
    }
  }
}
```
It returns 201 success. 

In Index Management - Transform Jobs, this job can be seen with ***Status: Error: Failed to search data in source indices.***

**What is the expected behavior?**
IN OS 2.5 or earlier version, transform does not support bucket_script in aggregation. It should throw exception to reflect this eror.

**What is your host/environment?**
 - OS: AWS Managed Service
 - Version: OS 1.3 & OS 2.3

**Comment by n-dohrmann** [comment]
Could I be assigned this issue? thanks!
