### ISSUE TITLE
[BUG] api/ism/_snapshots throws 502 after exactly 2 mins  

### ISSUE THREAD

**Issue by JustinasKO** [opensearch-project/index-management#680]
**What is the bug?**
when trying to list all snapshots in ISM snapshot management interface it times out after 2 mins.
We have thousands of snapshots in s3 repository and somehow GUI fails to list them like 4 times out of 5.
Refreshing multiple times sometimes request passes in like 1m 50s. Was trying to find if we have any timeout set on LB,
but all values are much higher. Also could not find anything related in configuration.
`GET _snapshot/s3-repository/_all` fails also when it takes longer then 2mins to get response.

**How can one reproduce the bug?**
Steps to reproduce the behaviour:
1. Place lots of snapshots to s3 (or maybe simulate somehow slow response)
2. Go to ISM -> Snapshot Management -> Snapshots
3. If it takes longer then 2mins to load you will get `GET https://my.opensearch.cluster/api/ism/_snapshots 502 - core.entry.js:15`        

**What is the expected behaviour?**
List of snapshots provided even if it takes longer then 2 mins

**What is your host/environment?**
 - OS: [official OpenSearch containers running on ARM64 K8s nodes]
 - Version [OpenSearch v2.4]
 - Plugins - standart + repository-s3

**Do you have any screenshots?**
no

**Do you have any additional context?**
no

**Comment by bowenlan-amzn** [comment]
I can confirm that this api/ism/_snapshots is using that API `Get _snapshot/<repo>/_all` behind the scene: https://github.com/opensearch-project/index-management-dashboards-plugin/blob/main/server/services/SnapshotManagementService.ts#L63-L67

The [GetSnapshotsRequest](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsRequest.java) request is a ClusterManagerNodeRequest with default timeout of 30s.

@opensearch-project/transfer-request can we transfer this to @opensearch-project/opensearch-core to find expert?
