### ISSUE TITLE
[BUG] Rollups - SearchRequest missing cancelAfterTimeInterval parameter

### ISSUE THREAD

**Issue by petardz** [opensearch-project/index-management#710]
**What is the bug?**
In RollupRunner we don't set cancelAfterTimeInterval parameter on SearchRequest object. Consequence of this is that global cluster setting **_search.cancel_after_time_interval_**  will override it, which if set too low, could impact rollup run success rate.

**How can one reproduce the bug?**
1. Set cluster setting **_search.cancel_after_time_interval_** to something very low, like 1s
2. Create rollup job on index with some number of documents/shards
3. See Cancellation timeout error (TaskCancelledExceptioncancelled exception)

**What is the expected behavior?**
Rollup job should have full control of this timeout.

**Comment by rishabhmaurya** [comment]
Are you proposing its resolution to be individual plugin's responsibility to set the `search.cancel_after_time_interval` with `max(cluster setting search.cancel_after_time_interval, plugin's default minimum value say 5s)` ?

**Comment by petardz** [comment]
@rishabhmaurya If I understood correctly, cluster `setting search.cancel_after_time_interval` will be used [only if same param in SearchRequest is null](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/support/TimeoutTaskCancellationUtility.java#L57)?

If that's the case, then plugin can override this setting but setting a value in every SearchRequest before calling _search

**Comment by rishabhmaurya** [comment]
relates to - https://github.com/opensearch-project/alerting/issues/827

**Comment by Joshua152** [comment]
Can I be assigned to this issue?
