### ISSUE TITLE
Integrate with Notification plugin

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/index-management#74]
Index State Management currently supports notifications (email, chime, custom webhook) using a notification jar that is packaged as part of index management plugin. We will integrate with notification plugin (https://github.com/opensearch-project/notifications), to have a centralized notification framework.

Integrate with notification plugin, without breaking existing API's on notification.
https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/policies/#notification

**Comment by qreshi** [comment]
@dbbaughe @bowenlan-amzn I believe this was completed via https://github.com/opensearch-project/index-management/pull/338 and https://github.com/opensearch-project/index-management-dashboards-plugin/pull/181.

Any other pending tasks? If not, we can close the issue.
