### ISSUE TITLE
[BUG] NullPointerException from IndexUtils.isConcreteIndex when searching rollup index

### ISSUE THREAD

**Issue by mark-VIII** [opensearch-project/index-management#764]
**What is the bug?**
Searching against a rollup index that was created by a rollup job using a wildcard within the source index parameter results in NullPointerException.

**How can one reproduce the bug?**
1. Create an index and populate it with documents
2. Roll the index over a few times
3. Create a rollup job with a wildcard in the source index that matches the previous rolled-over indices
4. Wait for the job to create the new rollup index
5. Execute a /_search on the rollup index
6. See error response with "status" 500  and root cause "null_pointer_exception"

Error log: 
[OS-error.txt](https://github.com/opensearch-project/index-management/files/11351257/OS-error.txt)

**What is the expected behavior?**
We expect the search to return expected results rather than an internal server error.

**What is your host/environment?**
 - OS: Linux
 - RHEL 8.x
 - Plugins: opensearch-index-management, opensearch-job-scheduler, opensearch-transport-ssl, repository-s3

**Do you have any screenshots?**
![9 46 98 128_30537_app_opensearch_index_management_dashboards](https://user-images.githubusercontent.com/44299364/234911085-a2561d97-da02-46cc-977a-ec3a908c758e.png)

**Do you have any additional context?**
If we search against a rollup index where the job used a single source index then we get expected results, so the wildcard is a key factor.

Index rollovers might not be a requirement to reproduce.

**Comment by praveensameneni** [comment]
Thank you @mark-VIII for submitting the issue. We are looking into it.

**Comment by mark-VIII** [comment]
Thank you for fixing the issue! 🎉
