### ISSUE TITLE
[BUG] can't have custom settings for internal indexes

### ISSUE THREAD

**Issue by celesteking** [opensearch-project/index-management#78]
This is a dev setup and I'd like my cluster to be always GREEN. With default config, all internal indexes are created with replica set to 1. I don't want this. What I want on this dev machine is to let me set that to zero.

This is what I use as template, but it doesn't work, it ignores the values.

```
{
  "order": 0,
  "index_patterns": [
    ".*"
  ],
  "settings": {
    "index": {
      "auto_expand_replicas": "0-all",
      "number_of_replicas": "0"
    }
  }
}
```

And this is what I get in the end:
```
{ - 
  ".opendistro-alerting-config": { - 
    "settings": { - 
      "index": { - 
        "hidden": "true",
        "number_of_shards": "1",
        "provided_name": ".opendistro-alerting-config",
        "number_of_replicas": "1",
      }
    }
  }
}
```
same with `.opendistro-alerting-alerts` and `.opendistro-alerting-alert-history-2021.06.11-1`, etc.

**Comment by thalurur** [comment]
@celesteking what version are you using currently? I have tried on our latest version of ODFE and opensearch and this is working as expected.

Having said that this behavior is not controlled by plugin but is from the core library feature.

**Comment by celesteking** [comment]
opendistroforelasticsearch-kibana-1.13.2-1.x86_64
opendistroforelasticsearch-1.13.2-1.x86_64

Thanks!
