### ISSUE TITLE
[BUG] Snapshot details shows snapshot name under "Repository"

### ISSUE THREAD

**Issue by andrross** [opensearch-project/index-management#900]
**Describe the bug**

The snapshot details pane shows the snapshot name underneath "Repository"

**To Reproduce**
1. Create a snapshot
2. Click on "Snapshots" in the "Snapshot Management" section
3. Click on the snapshot name
4. View the details pane on the right

**Expected behavior**
The repository name should be shown underneath "Repository"

**OpenSearch Version**
2.9.0

**Dashboards Version**
2.9.0

**Plugins**

None

**Screenshots**

![261717091-03952479-e8c5-45b4-a7aa-858f9cb664d1](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/9160839/93b1038e-e3bf-4930-9c32-d3227d2db6a9)

**Host/Environment (please complete the following information):**
 - OS: OSD running on Ubuntu, browser running on Mac
 - Browser and version: Firefox 115.0.2

**Comment by bbarani** [comment]
@kavilla @zhongnansu I transferred it to ISM plugin repo. Did you mean ISM dashboards plugin repo?

**Comment by ict-one-nl** [comment]
Thanks for following up @andrross :)

**Comment by andrross** [comment]
I think this is a duplicate of https://github.com/opensearch-project/index-management-dashboards-plugin/issues/822

Which has been fixed by https://github.com/opensearch-project/index-management-dashboards-plugin/pull/824

I'm going to close this issue.
