### ISSUE TITLE
[BUG]Could not create task ':renameDeb'.

### ISSUE THREAD

**Issue by xiaodizi** [opensearch-project/index-management#905]
I downloaded the source code, and after importing IDEA, the following error occurred when I Sync. I did not find the relevant instructions in the development manual, why is this?
<img width="1525" alt="image" src="https://github.com/opensearch-project/index-management/assets/10411525/8a2c8a8b-571e-4069-8315-7de5a12ae920">

I use mac os, jdk11.

`Could not create task ':renameDeb'.
No signature of method: org.gradle.api.tasks.Copy.include() is applicable for argument types: (org.gradle.api.internal.provider.DefaultProperty) values: [task ':buildDeb' property 'archiveFileName']
Possible solutions: include([Ljava.lang.String;), include(groovy.lang.Closure), include(java.lang.Iterable), include(org.gradle.api.specs.Spec), include([Ljava.lang.String;), include(groovy.lang.Closure)
Could not find method include() for arguments [task ':buildDeb' property 'archiveFileName'] on task ':renameDeb' of type org.gradle.api.tasks.Copy.
`

**Comment by Hailong-am** [comment]
@xiaodizi what's the gradle setup of your IDEA?

**Comment by xiaodizi** [comment]
> @xiaodizi what's the gradle setup of your IDEA?

<img width="1635" alt="image" src="https://github.com/opensearch-project/index-management/assets/10411525/b8418f8b-ae94-4cd8-a2eb-f57fb7dc2048">
This is my Settings！！！

**Comment by Hailong-am** [comment]
@xiaodizi please refer changes in this PR https://github.com/opensearch-project/index-management/pull/916
