### ISSUE TITLE
Don't replace detector's backend role when update

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/index-management#98]
Check more details https://github.com/opensearch-project/anomaly-detection/issues/124

Create tracking issues for each plugin to follow the same design.

**Comment by dbbaughe** [comment]
Eh... I don't think we'll follow this pattern in Index Management. It's going to be an extremely bad workflow if the roles cannot be updated for these jobs that are long-living and are based on previous executions. I think the better alternative is to allow users to choose which roles/permissions should be stored on the job. By default you can have it not automatically update the background roles and instead just keep them as-is, but if the user does want to update them then they can make that choice.

**Comment by dbbaughe** [comment]
As noted before, this would not be beneficial to ISM users and provide a bad CX if they cannot update a jobs permissions. Closing.
